In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Strain of fiber filled matrix (mode 7-9)

In [7]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_fibers\\'
fname7 = 'out_ALLELEMENTS_EE_frame_0007.npy'
ee11fib7 = np.load(folder+fname7)

print ee11fib7

[-8.39941650e-05  5.41088777e-05  1.17786734e-05  7.08196919e-04
 -2.41430488e-03 -5.25587972e-04]


In [8]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_fibers\\'
fname8 = 'out_ALLELEMENTS_EE_frame_0008.npy'
ee11fib8 = np.load(folder+fname8)

print ee11fib8

[ 2.99730709e-04  6.26170004e-04 -1.45940798e-03  5.64677121e-04
  1.47106004e-03  4.76754201e-05]


In [9]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_fibers\\'
fname9 = 'out_ALLELEMENTS_EE_frame_0009.npy'
ee11fib9 = np.load(folder+fname9)

print ee11fib9

[ 0.00015184  0.00029103 -0.00051182 -0.00519104 -0.00704778 -0.00033582]


Stress of fiber filled matrix (mode 7-9)

In [19]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_fibers\\'
fname7 = 'out_ALLELEMENTS_s_frame_0007.npy'
sfib7 = np.load(folder+fname7)

print sfib7

[ -1647340.30654532   1762556.28596157   -132671.17351135
  10194579.05692741 -35280128.13155646 -15471329.78237147]


In [20]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_fibers\\'
fname8 = 'out_ALLELEMENTS_s_frame_0008.npy'
sfib8 = np.load(folder+fname8)

print sfib8

[ 7.85357798e+06  3.21860533e+07 -1.24810012e+08 -1.60721355e+07
  5.04954993e+07 -3.98079619e+06]


In [21]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_fibers\\'
fname9 = 'out_ALLELEMENTS_s_frame_0009.npy'
sfib9 = np.load(folder+fname9)

print sfib9

[ 5.28212180e+06  1.44779922e+07 -3.09093628e+07 -1.47896726e+08
 -2.09604162e+08 -8.43583211e+06]


Strain of sphere filled matrix (mode 7-9)

In [26]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_sph\\'
fname7 = 'out_ALLELEMENTS_EE_frame_0007.npy'
ee11sph7 = np.load(folder+fname7)

print ee11sph7

[ 8.30017920e-05 -4.22032497e-05  9.21397094e-05  2.87699671e-04
  2.10588217e-03  9.81920329e-04]


In [27]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_sph\\'
fname8 = 'out_ALLELEMENTS_EE_frame_0008.npy'
ee11sph8 = np.load(folder+fname8)

print ee11sph8

[ 0.00078446  0.00084803 -0.00218604  0.00077008 -0.00124525  0.00110075]


In [28]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_sph\\'
fname9 = 'out_ALLELEMENTS_EE_frame_0009.npy'
ee11sph9 = np.load(folder+fname9)

print ee11sph9

[-0.00049278 -0.00051255  0.0011254  -0.00319802  0.00659385 -0.00103924]


Stress of fiber filled matrix (mode 7-9)

In [29]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_sph\\'
fname7 = 'out_ALLELEMENTS_s_frame_0007.npy'
ssph7 = np.load(folder+fname7)

print ssph7

[ 1623852.01117703 -1633423.64913541  3123456.30758359  4803521.10069237
 41501504.78215814 19728905.31139258]


In [30]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_sph\\'
fname8 = 'out_ALLELEMENTS_s_frame_0008.npy'
ssph8 = np.load(folder+fname8)

print ssph8

[ 2.37945957e+07  3.25796342e+07 -1.42967795e+08  2.53744337e+07
 -2.43068976e+07  5.16001189e+07]


In [31]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_sph\\'
fname9 = 'out_ALLELEMENTS_s_frame_0009.npy'
ssph9 = np.load(folder+fname9)

print ssph9

[-1.48113811e+07 -1.96343940e+07  6.74248698e+07 -9.70149146e+07
  2.31382826e+08 -3.66109855e+07]


Strain of base matrix (mode 7-9)

In [32]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_matrix\\'
fname7 = 'out_ALLELEMENTS_EE_frame_0007.npy'
ee11mat7 = np.load(folder+fname7)

print ee11mat7

[ 7.89463247e-11 -2.84019562e-11 -4.07960515e-11 -1.94116175e-10
 -6.03583387e-11  3.42901625e-10]


In [34]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_matrix\\'
fname8 = 'out_ALLELEMENTS_EE_frame_0008.npy'
ee11mat8 = np.load(folder+fname8)

print ee11mat8

[-2.28729683e-09  1.32698033e-09  1.42565754e-09 -3.46474497e-11
  8.64646154e-10  3.14663074e-10]


In [35]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_matrix\\'
fname9 = 'out_ALLELEMENTS_EE_frame_0009.npy'
ee11mat9 = np.load(folder+fname9)

print ee11mat9

[-7.41102736e-10  7.27654658e-10  2.77035618e-10  2.09314801e-10
  2.24486497e-10 -6.79225247e-11]


Stress of fiber filled matrix (mode 7-9)

In [36]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_matrix\\'
fname7 = 'out_ALLELEMENTS_s_frame_0007.npy'
smat7 = np.load(folder+fname7)

print smat7

[ 6.69765067 -1.58510641 -2.55440519 -7.50825857 -2.14111155 13.10773591]


In [37]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_matrix\\'
fname8 = 'out_ALLELEMENTS_s_frame_0008.npy'
smat8 = np.load(folder+fname8)

print smat8

[-149.38963447  128.71128516  137.00858631   -1.28701064   33.49438016
   12.09051464]


In [38]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_matrix\\'
fname9 = 'out_ALLELEMENTS_s_frame_0009.npy'
smat9 = np.load(folder+fname9)

print smat9

[-41.78048943  71.27386025  36.58504996   8.0317827    8.70296562
  -2.68265867]


Strain of Homgonized matrix (mode 7-9)

In [39]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_avgE\\'
fname7 = 'out_ALLELEMENTS_EE_frame_0007.npy'
ee11avgE7 = np.load(folder+fname7)

print ee11avgE7

[ 7.00222080e-05 -3.63067861e-05  5.51948865e-05  2.43700806e-04
  1.60185529e-03  7.86597706e-04]


In [34]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_avgE\\'
fname8 = 'out_ALLELEMENTS_EE_frame_0008.npy'
ee11avgE8 = np.load(folder+fname8)

print ee11avgE8

[-2.28729683e-09  1.32698033e-09  1.42565754e-09 -3.46474497e-11
  8.64646154e-10  3.14663074e-10]


In [40]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\ee_post_set_averages_avgE\\'
fname9 = 'out_ALLELEMENTS_EE_frame_0009.npy'
ee11avgE9 = np.load(folder+fname9)

print ee11avgE9

[-0.00037957 -0.00042898  0.00090782 -0.00266013  0.00517381 -0.00079727]


Stress of fiber filled matrix (mode 7-9)

In [41]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_avgE\\'
fname7 = 'out_ALLELEMENTS_s_frame_0007.npy'
savgE7 = np.load(folder+fname7)

print savgE7

[ 1794867.11811395 -1931883.05443268  2619904.48376987  5429147.66648281
 43353321.11556622 21301103.54945024]


In [42]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_avgE\\'
fname8 = 'out_ALLELEMENTS_s_frame_0008.npy'
savgE8 = np.load(folder+fname8)

print savgE8

[ 2.55395530e+07  3.99135632e+07 -1.60396528e+08  2.86391967e+07
 -2.58797005e+07  5.94442197e+07]


In [44]:
folder = 'C:\\Users\\mason\\Documents\\Python Scripts\\rus-project\\averages\\s_post_set_averages_avgE\\'
fname9 = 'out_ALLELEMENTS_s_frame_0009.npy'
savgE9 = np.load(folder+fname9)

print savgE9

[-1.52183925e+07 -2.26599711e+07  7.41802024e+07 -1.10028565e+08
  2.47678700e+08 -3.91305144e+07]
